properties([pipelineTriggers([githubPush()])])

pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: nodejs
    image: docker-registry.default.svc:5000/openshift/nodejs
    command:
    - cat
    tty: true
"""
    }
  }
  stages {
    stage('Test webui') {
      git branch: 'stable-ocp-3.11', url: 'https://github.com/kovarus/coolstore-microservice.git'
      steps {
        container('nodejs') {
          cd 'ls'
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
  }
}
