properties([pipelineTriggers([githubPush()])])

pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: nodejs
    image: docker-registry.default.svc:5000/openshift/nodejs
    command:
    - cat
    tty: true
    privileged: true
"""
    }
  }
  stages {
    stage('Test webui') {
      steps {
        container('jnlp') {
          sh 'chmod -R g+w /home/jenkins/agent/workspace'
        }
        container('nodejs') {
          sh 'ls'
          sh 'cd coolstore-webui/coolstore-ui'
        }
      }
    }
  }
}
